---
id: introduction-of-the-elixir-lang-at-ruby-sapporo-28
base_name: introducition-of-the-elixir-lang-at-ruby-sapporo-28
tags:
- elixir-lang
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :markdown
  name: niku
  email: niku@niku.name
  rubygems_user: niku
  slideshare_user: 
  speaker_deck_user: niku
